docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query restauranteslateral --number 10 --source facebook --algorithm sentiment140 --lang es --id 21 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@rest_lateral" --number 50 --source twitter --algorithm sentiment140 --lang es --id 22 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query 100MontaditosSpain --number 10 --source facebook --algorithm sentiment140 --lang es --id 23 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@100montaditos" --number 50 --source twitter --algorithm sentiment140 --lang es --id 24 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "restaurantes lateral" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 25 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "100 montaditos" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 26 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Cervecería La Sureña" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 27 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Lizarran" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 28 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "cerveceria.la.surena" --number 10 --source facebook --algorithm sentiment140 --lang es --id 29 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@La__Surena" --number 50 --source twitter --algorithm sentiment140 --lang es --id 210 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "LizarranBar" --number 10 --source facebook --algorithm sentiment140 --lang es --id 211 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@lizarranbar" --number 50 --source twitter --algorithm sentiment140 --lang es --id 212 --doc-type lizarran
