docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query restauranteslateral --number 10 --source facebook --algorithm sentiment140 --lang es --id 1 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@rest_lateral" --number 50 --source twitter --algorithm sentiment140 --lang es --id 2 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query 100MontaditosSpain --number 10 --source facebook --algorithm sentiment140 --lang es --id 3 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@100montaditos" --number 50 --source twitter --algorithm sentiment140 --lang es --id 4 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "restaurantes lateral" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 5 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "100 montaditos" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 6 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Cervecería La Sureña" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 7 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Lizarran" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 8 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "cerveceria.la.surena" --number 50 --source facebook --algorithm sentiment140 --lang es --id 9 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@La__Surena" --number 50 --source twitter --algorithm sentiment140 --lang es --id 10 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "LizarranBar" --number 50 --source facebook --algorithm sentiment140 --lang es --id 11 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "lizarran" --number 50 --source twitter --algorithm sentiment140 --lang es --id 12 --doc-type lizarran
