docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query restauranteslateral --number 10 --source facebook --algorithm sentiment140 --lang es --id 31 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@rest_lateral" --number 50 --source twitter --algorithm sentiment140 --lang es --id 32 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query 100MontaditosSpain --number 10 --source facebook --algorithm sentiment140 --lang es --id 33 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@100montaditos" --number 50 --source twitter --algorithm sentiment140 --lang es --id 34 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "restaurantes lateral" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 35 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "100 montaditos" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 36 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Cervecería La Sureña" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 37 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Lizarran" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 38 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "cerveceria.la.surena" --number 10 --source facebook --algorithm sentiment140 --lang es --id 39 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@La__Surena" --number 50 --source twitter --algorithm sentiment140 --lang es --id 310 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "LizarranBar" --number 10 --source facebook --algorithm sentiment140 --lang es --id 311 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@lizarranbar" --number 50 --source twitter --algorithm sentiment140 --lang es --id 312 --doc-type lizarran
